# version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - inventory-service
    networks:
      - app-network

  inventory-service:
    build:
      context: ./inventory-service
    container_name: inventory-service
    ports:
      - "3001:3001"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
                                                                 